name: Deploy Cloud Functions

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: freescheduleapp # The ID of your Firebase/GCP project
  # GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  functions:
    name: Deploy Cloud Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      # Environment variables
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SENDINBLUE_API_KEY: "${{ secrets.SENDINBLUE_API_KEY }}"
          envkey_SERVICE_ACCOUNT_PROJECT_ID: "${{ secrets.SERVICE_ACCOUNT_PROJECT_ID }}"
          envkey_SERVICE_ACCOUNT_CLIENT_EMAIL: "${{ secrets.SERVICE_ACCOUNT_CLIENT_EMAIL }}"
          envkey_SERVICE_ACCOUNT_PRIVATE_KEY: "${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}"
          directory: functions
      - name: Use Node 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Install dependencies
        run: cd functions && npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.0.3
        with:
          args: deploy --only functions
  webapp:
    name: Deploy Web App to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      # Environment variables
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_STRIPE_PRICE_ID: "${{ vars.VITE_STRIPE_PRICE_ID }}"
          envkey_VITE_FIREBASE_API_KEY: "${{ secrets.VITE_FIREBASE_API_KEY }}"
          envkey_VITE_FIREBASE_AUTH_DOMAIN: "${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}"
          envkey_VITE_FIREBASE_PROJECT_ID: "${{ vars.VITE_FIREBASE_PROJECT_ID }}"
          envkey_VITE_FIREBASE_STORAGE_BUCKET: "${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}"
          envkey_VITE_FIREBASE_MESSAGING_SENDER_ID: "${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}"
          envkey_VITE_FIREBASE_APP_ID: "${{ secrets.VITE_FIREBASE_APP_ID }}"
          envkey_VITE_FIREBASE_MEASUREMENT_ID: "${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}"
          envkey_VITE_SA_CLIENT_EMAIL: "${{ secrets.VITE_SA_CLIENT_EMAIL }}"
          envkey_VITE_SA_PRIVATE_KEY: "${{ secrets.VITE_SA_PRIVATE_KEY }}"
          envkey_VITE_MODE: "${{ vars.VITE_MODE }}"
      - name: Use Node 20.x
        uses: actions/setup-node@master
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.0.3
        with:
          args: deploy --only hosting:schedulify-pro
